# Generated by Django 5.0.14 on 2025-07-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('administrador_id', models.BigIntegerField(db_column='Administrador_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoColectivo',
            fields=[
                ('grupo_colectivo_id', models.BigAutoField(db_column='Grupo_colectivo_id', primary_key=True, serialize=False)),
                ('grupo_colectivo_nombre', models.CharField(db_column='Grupo_colectivo_nombre', max_length=255)),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
            ],
            options={
                'db_table': 'grupo_colectivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('medico_id', models.BigAutoField(db_column='Medico_id', primary_key=True, serialize=False)),
                ('medico_apaterno', models.CharField(db_column='Medico_apaterno', max_length=255)),
                ('medico_amaterno', models.CharField(blank=True, db_column='Medico_amaterno', max_length=255, null=True)),
                ('medico_rut', models.CharField(db_column='Medico_rut', max_length=255)),
                ('medico_fecha_nacimiento', models.DateField(db_column='Medico_fecha_nacimiento')),
                ('medico_telefono', models.CharField(db_column='Medico_telefono', max_length=255)),
                ('medico_centro_atencion', models.CharField(db_column='Medico_centro_atencion', max_length=255)),
                ('medico_genero', models.CharField(db_column='Medico_genero', max_length=9)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NarrativaArchivo',
            fields=[
                ('narrativa_archivo_id', models.BigIntegerField(db_column='Narrativa_archivo_id', primary_key=True, serialize=False)),
                ('narrativa_archivo_url', models.CharField(db_column='Narrativa_archivo_url', max_length=255)),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
            ],
            options={
                'db_table': 'narrativa_archivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NarrativaEscrita',
            fields=[
                ('narrativa_id', models.BigAutoField(db_column='Narrativa_id', primary_key=True, serialize=False)),
                ('narrativa_escrita_contenido', models.TextField(db_column='Narrativa_escrita_contenido')),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
            ],
            options={
                'db_table': 'narrativa_escrita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacion_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('notificacion_visto', models.IntegerField(db_column='Notificacion_visto')),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.BigAutoField(db_column='Paciente_id', primary_key=True, serialize=False)),
                ('paciente_rut', models.CharField(db_column='Paciente_rut', max_length=255)),
                ('paciente_apaterno', models.CharField(db_column='Paciente_apaterno', max_length=255)),
                ('paciente_amaterno', models.CharField(blank=True, db_column='Paciente_amaterno', max_length=255, null=True)),
                ('paciente_genero', models.CharField(db_column='Paciente_genero', max_length=9)),
                ('paciente_fecha_nacimiento', models.DateField(db_column='Paciente_fecha_nacimiento')),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacienteGrupo',
            fields=[
                ('paciente_grupo_id', models.BigIntegerField(db_column='Paciente_Grupo_id', primary_key=True, serialize=False)),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
            ],
            options={
                'db_table': 'paciente_grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacienteMedico',
            fields=[
                ('paciente_medico_id', models.BigIntegerField(db_column='Paciente_Medico_id', primary_key=True, serialize=False)),
                ('paciente_medico_validado', models.IntegerField()),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
            ],
            options={
                'db_table': 'paciente_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.BigAutoField(db_column='Usuario_id', primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(db_column='Usuario_nombre', max_length=255)),
                ('usuario_correo', models.CharField(db_column='Usuario_correo', max_length=255)),
                ('usuario_contrasenia', models.CharField(db_column='Usuario_contrasenia', max_length=255)),
                ('usuario_rol', models.CharField(db_column='Usuario_rol', max_length=8)),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
