# Generated by Django 5.0.14 on 2025-10-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narrativaarchivo',
            options={},
        ),
    ]
