# Generated by Django 5.0.14 on 2025-10-06 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_narrativaarchivo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativaarchivo',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
        migrations.AlterField(
            model_name='narrativaarchivo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='narrativaarchivo',
            name='narrativa_archivo_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='narrativaarchivo',
            name='narrativa_archivo_url',
            field=models.FileField(upload_to='narrativas/'),
        ),
        migrations.AlterField(
            model_name='narrativaarchivo',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
