# Generated by Django 5.0.14 on 2025-10-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_narrativaarchivo_paciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narrativaarchivo',
            old_name='paciente',
            new_name='paciente_id',
        ),
    ]
