# Generated by Django 5.0.14 on 2025-10-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_paciente_narrativaarchivo_paciente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narrativaarchivo',
            old_name='paciente_id',
            new_name='paciente',
        ),
    ]
